apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:yM6NwUjlaY884MXMDNP/kOkb1hNdZpplomvmKZ/EvRkCerPV/XMprIUCKfkWKIYE4l+e/OGv4VBB4pk6FsbIF2Rr71g5bjh5UW9JSeH+yZYu87kw7FllAC+H377YYrH9GfveUianenMwBPveSt2ri2a3G2qV9SoAt0BoDQ==,iv:TnyhcpsjRphayw6OIDVDo3RZbxDR3EAxVL6OUwiOaPk=,tag:XNE6OShVbJ9s7nX8n12qAA==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age1njw3753qrva6ezyupp73xnq004f7p5t7cak63k2rs99ghqmsqswqh6n60x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM3hIKzdiNis2cDJFS0RG
            TEpla3l3QnJXRmRvLzRkc2xyZG9XQjlGWVIwCldKVm9zbUJpSDBxd3NCcGVDZnhD
            VWpkUzJHYyt0Q0FqeWlGbEdDemVvaE0KLS0tIHdNdVdlSnM1VHdIdjY2Q29aTXFL
            K2xtTFJLejQxTEZkR0lhU3lEZFZEYWMKuc0wkJlKXww1glg/izw1wXcLlPdyWEQT
            IgJ/3KM/NQRkgYFk+id69DL4CuSOOPjlXFqAUSVb2pk3F3nejK/ioA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T01:33:32Z"
    mac: ENC[AES256_GCM,data:/fUNlrY7apN19XPbmI4gsoeL+0GL/Pzyh+ANcQ5fy6KiTuzuIHKPz1STF2Vue3Wuq2uBRBZgoRc1hBwpQfjKxAvPZKmx6N700b5i2K6suOr7Zgx37VmdbtpPzRjLqdS2Sv/Xhqa9u4Q4Vck/pmdFWZ3Fm+bVQev7lzfvOUBSXRw=,iv:lvk5NB7tp7zdqfS2r04AHwvXprNZIsC3pnrzN5LcvoM=,tag:qP3+YkwAZBZ1EOv+XmF7sw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
