apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../base/kube-prometheus-stack/
  - grafana-credentials.yaml
  - grafana-tls-cert-selfsign.yaml

patches:
  - path: release-patch-tls.yaml
    target:
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring
