apiVersion: v1
kind: Service
metadata:
  labels:
    name: audiobookshelf
  namespace: audiobookshelf
  name: audiobookshelf
spec:
  ports:
    - port: 13378
  selector:
    app: audiobookshelf
  type: ClusterIP
